name: Cerritos Animation
favicon: null
layout_spectrum: 0.047846512170508504
typography_spectrum: 0.6256449695210904
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.3180355951189995
  lightness: 0.13910112855955958
  saturation: 0.0446491907350719
  rhythmicContrast: 0.027596015017479658
purpose: []
